package com.example.ngajitime.util

import com.example.ngajitime.data.local.entity.SurahProgress

object DataSurah {
    val list114Surah = listOf(
        SurahProgress(1, "Al-Fatihah", "Pembukaan", 7),
        SurahProgress(2, "Al-Baqarah", "Sapi Betina", 286),
        SurahProgress(3, "Ali 'Imran", "Keluarga Imran", 200),
        SurahProgress(4, "An-Nisa'", "Wanita", 176),
        SurahProgress(5, "Al-Ma'idah", "Hidangan", 120),
        SurahProgress(6, "Al-An'am", "Binatang Ternak", 165),
        SurahProgress(7, "Al-A'raf", "Tempat Tertinggi", 206),
        SurahProgress(8, "Al-Anfal", "Rampasan Perang", 75),
        SurahProgress(9, "At-Taubah", "Pengampunan", 129),
        SurahProgress(10, "Yunus", "Nabi Yunus", 109),
        SurahProgress(11, "Hud", "Nabi Hud", 123),
        SurahProgress(12, "Yusuf", "Nabi Yusuf", 111),
        SurahProgress(13, "Ar-Ra'd", "Guruh", 43),
        SurahProgress(14, "Ibrahim", "Nabi Ibrahim", 52),
        SurahProgress(15, "Al-Hijr", "Gunung Berbatu", 99),
        SurahProgress(16, "An-Nahl", "Lebah", 128),
        SurahProgress(17, "Al-Isra'", "Perjalanan Malam", 111),
        SurahProgress(18, "Al-Kahf", "Gua", 110),
        SurahProgress(19, "Maryam", "Siti Maryam", 98),
        SurahProgress(20, "Ta Ha", "Ta Ha", 135),
        SurahProgress(21, "Al-Anbiya'", "Para Nabi", 112),
        SurahProgress(22, "Al-Hajj", "Haji", 78),
        SurahProgress(23, "Al-Mu'minun", "Orang-orang Mukmin", 118),
        SurahProgress(24, "An-Nur", "Cahaya", 64),
        SurahProgress(25, "Al-Furqan", "Pembeda", 77),
        SurahProgress(26, "Asy-Syu'ara'", "Para Penyair", 227),
        SurahProgress(27, "An-Naml", "Semut", 93),
        SurahProgress(28, "Al-Qasas", "Kisah-kisah", 88),
        SurahProgress(29, "Al-Ankabut", "Laba-laba", 69),
        SurahProgress(30, "Ar-Rum", "Bangsa Romawi", 60),
        SurahProgress(31, "Luqman", "Keluarga Luqman", 34),
        SurahProgress(32, "As-Sajdah", "Sujud", 30),
        SurahProgress(33, "Al-Ahzab", "Golongan Bersekutu", 73),
        SurahProgress(34, "Saba'", "Kaum Saba'", 54),
        SurahProgress(35, "Fatir", "Pencipta", 45),
        SurahProgress(36, "Ya Sin", "Ya Sin", 83),
        SurahProgress(37, "As-Saffat", "Barisan-barisan", 182),
        SurahProgress(38, "Sad", "Sad", 88),
        SurahProgress(39, "Az-Zumar", "Rombongan", 75),
        SurahProgress(40, "Ghafir", "Yang Mengampuni", 85),
        SurahProgress(41, "Fussilat", "Yang Dijelaskan", 54),
        SurahProgress(42, "Asy-Syura", "Musyawarah", 53),
        SurahProgress(43, "Az-zukhruf", "Perhiasan", 89),
        SurahProgress(44, "Ad-Dukhan", "Kabut", 59),
        SurahProgress(45, "Al-Jasiyah", "Yang Berlutut", 37),
        SurahProgress(46, "Al-Ahqaf", "Bukit Pasir", 35),
        SurahProgress(47, "Muhammad", "Nabi Muhammad", 38),
        SurahProgress(48, "Al-Fath", "Kemenangan", 29),
        SurahProgress(49, "Al-Hujurat", "Kamar-kamar", 18),
        SurahProgress(50, "Qaf", "Qaf", 45),
        SurahProgress(51, "Az-Zariyat", "Angin yang Menerbangkan", 60),
        SurahProgress(52, "At-Tur", "Bukit", 49),
        SurahProgress(53, "An-Najm", "Bintang", 62),
        SurahProgress(54, "Al-Qamar", "Bulan", 55),
        SurahProgress(55, "Ar-Rahman", "Yang Maha Pemurah", 78),
        SurahProgress(56, "Al-Waqi'ah", "Hari Kiamat", 96),
        SurahProgress(57, "Al-Hadid", "Besi", 29),
        SurahProgress(58, "Al-Mujadilah", "Wanita Menggugat", 22),
        SurahProgress(59, "Al-Hasyr", "Pengusiran", 24),
        SurahProgress(60, "Al-Mumtahanah", "Wanita yang Diuji", 13),
        SurahProgress(61, "As-Saff", "Barisan", 14),
        SurahProgress(62, "Al-Jumu'ah", "Hari Jumat", 11),
        SurahProgress(63, "Al-Munafiqun", "Orang-orang Munafik", 11),
        SurahProgress(64, "At-Tagabun", "Hari Ditampakkan Kesalahan", 18),
        SurahProgress(65, "At-Talaq", "Talak", 12),
        SurahProgress(66, "At-Tahrim", "Mengharamkan", 12),
        SurahProgress(67, "Al-Mulk", "Kerajaan", 30),
        SurahProgress(68, "Al-Qalam", "Pena", 52),
        SurahProgress(69, "Al-Haqqah", "Hari Kiamat", 52),
        SurahProgress(70, "Al-Ma'arij", "Tempat Naik", 44),
        SurahProgress(71, "Nuh", "Nabi Nuh", 28),
        SurahProgress(72, "Al-Jinn", "Jin", 28),
        SurahProgress(73, "Al-Muzzammil", "Orang Berselimut", 20),
        SurahProgress(74, "Al-Muddassir", "Orang Berkemul", 56),
        SurahProgress(75, "Al-Qiyamah", "Hari Kiamat", 40),
        SurahProgress(76, "Al-Insan", "Manusia", 31),
        SurahProgress(77, "Al-Mursalat", "Malaikat yang Diutus", 50),
        SurahProgress(78, "An-Naba'", "Berita Besar", 40),
        SurahProgress(79, "An-Nazi'at", "Malaikat Pencabut", 46),
        SurahProgress(80, "'Abasa", "Ia Bermuka Masam", 42),
        SurahProgress(81, "At-Takwir", "Menggulung", 29),
        SurahProgress(82, "Al-Infitar", "Terbelah", 19),
        SurahProgress(83, "Al-Mutaffifin", "Orang Curang", 36),
        SurahProgress(84, "Al-Insyiqaq", "Terbelah", 25),
        SurahProgress(85, "Al-Buruj", "Gugusan Bintang", 22),
        SurahProgress(86, "At-Tariq", "Yang Datang Malam", 17),
        SurahProgress(87, "Al-A'la", "Yang Paling Tinggi", 19),
        SurahProgress(88, "Al-Ghasyiyah", "Hari Pembalasan", 26),
        SurahProgress(89, "Al-Fajr", "Fajar", 30),
        SurahProgress(90, "Al-Balad", "Negeri", 20),
        SurahProgress(91, "Asy-Syams", "Matahari", 15),
        SurahProgress(92, "Al-Lail", "Malam", 21),
        SurahProgress(93, "Ad-Duha", "Waktu Duha", 11),
        SurahProgress(94, "Al-Insyirah", "Kelapangan", 8),
        SurahProgress(95, "At-Tin", "Buah Tin", 8),
        SurahProgress(96, "Al-'Alaq", "Segumpal Darah", 19),
        SurahProgress(97, "Al-Qadr", "Kemuliaan", 5),
        SurahProgress(98, "Al-Bayyinah", "Bukti", 8),
        SurahProgress(99, "Az-Zalzalah", "Kegoncangan", 8),
        SurahProgress(100, "Al-'Adiyat", "Kuda Perang", 11),
        SurahProgress(101, "Al-Qari'ah", "Hari Kiamat", 11),
        SurahProgress(102, "At-Takasur", "Bermegah-megahan", 8),
        SurahProgress(103, "Al-'Asr", "Masa", 3),
        SurahProgress(104, "Al-Humazah", "Pengumpat", 9),
        SurahProgress(105, "Al-Fil", "Gajah", 5),
        SurahProgress(106, "Quraisy", "Suku Quraisy", 4),
        SurahProgress(107, "Al-Ma'un", "Barang Berguna", 7),
        SurahProgress(108, "Al-Kautsar", "Nikmat Banyak", 3),
        SurahProgress(109, "Al-Kafirun", "Orang Kafir", 6),
        SurahProgress(110, "An-Nasr", "Pertolongan", 3),
        SurahProgress(111, "Al-Lahab", "Gejolak Api", 5),
        SurahProgress(112, "Al-Ikhlas", "Ikhlas", 4),
        SurahProgress(113, "Al-Falaq", "Waktu Subuh", 5),
        SurahProgress(114, "An-Nas", "Manusia", 6)
    )
}